# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AEGIS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AEGIS
	pod 'CocoaMQTT'

  target 'AEGISTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AEGISUITests' do
    # Pods for testing
  end

end
