//
// Created by Emin Tunc Kirimlioglu on 4/26/23.
//

#ifndef ECE_140B_SPRING_2023_FINAL_PROJECT_AEGIS_NEW_SOLAR_HPP
#define ECE_140B_SPRING_2023_FINAL_PROJECT_AEGIS_NEW_SOLAR_HPP


class Solar {

};


#endif //ECE_140B_SPRING_2023_FINAL_PROJECT_AEGIS_NEW_SOLAR_HPP
